server.port=${SERVER_PORT:8081}

spring.datasource.url=${PG_URL:jdbc:postgresql://localhost:15432/tavall?currentSchema=contractors}
spring.datasource.username=${PG_USER:novus}
spring.datasource.password=${PG_PASS:d9gHyhsFad@@83#8HkWo}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.default_schema=${PG_SCHEMA:contractors}
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:db/contractors.sql

spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27020/tavall_contractors}
spring.data.mongodb.username=${MONGO_USER:tavall}
spring.data.mongodb.password=${MONGO_PASS:*Das9dh$%fhfajd#andaDAfN*S}
spring.data.mongodb.database=${MONGO_DB:tavall_contractors}

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:tavall-placeholder-google}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:tavall-placeholder-google-secret}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID:Iv23li7VB1MdanDa6Ae7}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET:b6bb0fa4d160a36271c6526533bee4a43176d08a}
spring.security.oauth2.client.registration.github.scope=read:user,user:email